version: '3'

services:
  traefik:
    image: traefik:v2.1
    container_name: traefik
    command:
      # Enable dashboard
      - --api.dashboard=true
      # Allow use API and dashboard though insecure
      - --api.insecure=true
      # Use docker as provider
      - --providers.docker=true
      # Enable log income requsts
      - --accesslog=true
      # Set log level (default ERROR)
      - --log.level=ERROR
      # Define entrypoint that listens 80 port
      - --entryPoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # Mount docker socker from host machine
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: whoami
    labels:
      # Create a route `whoami` and bound with defined entrypoint
      - traefik.http.routers.whoami.entrypoints=web
      # Create rule
      - traefik.http.routers.whoami.rule=Host(`whoami.example.com`)
